/**
 * TypeScript declarations for .psr files
 * Auto-generated by @pulsar-framework/vite-plugin
 * 
 * Wildcard allows any named exports from .psr files.
 * Use: import { ComponentName } from './file.psr'
 */
declare module '*.psr';
